services:
  armstracker-postgres:
    image: postgres
    env_file:
      - '.env'
    networks:
      - armstracker
    ports:
      - ${POSTGRES_PORT}:5432

networks:
  armstracker:
    driver: bridge