name: Run Tests

on: 
  pull_request:
    types: [opened, reopened, synchronize]

env:
  DB_PATH='./database'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: update pip
        run: pip install --upgrade pip
      - name: Install package
        run: pip install .
      - name: Create logs
        run: mkdir logs && touch logs/data_scrapers_get_conflict_belligerents
      - name: Run tests
        run: pytest taro/tests