name: Run Tests
on: 
  pull_request:
    types: [opened]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install pytest
        run pip install pytest
      - name: Run tests
        run: pytest tests